name: OS X (x86_64/arm64)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  osx:
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.9
      SDL_VERSION: 2.30.3
      FLAC_VERSION: 1.4.3
      LIBOGG_VERSION: 1.3.5
    
    steps:
      - name: 'Install dependencies'
        run: |
          brew install automake zip cmake wget

      - name: 'chown SDK directory'
        id: chown
        run: |
          sudo mkdir -p /Library/Developer/CommandLineTools/SDKs/MacOSX10.9.sdk
          sudo chown $(whoami) /Library/Developer/CommandLineTools/SDKs/MacOSX10.9.sdk /usr/local/lib

      - name: 'Cache SDK'
        uses: actions/cache@v4
        id: cache
        with:
          path: '/Library/Developer/CommandLineTools/SDKs/MacOSX10.9.sdk/'
          key: 10.9-SDK-Folder

      - name: 'Download SDK'
        id: download
        run: |
          if [ -z "$(ls -A /Library/Developer/CommandLineTools/SDKs/MacOSX10.9.sdk)" ]; then
            wget -nc "https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.9.sdk.tar.xz"
            sudo tar -xJf MacOSX10.9.sdk.tar.xz -C /Library/Developer/CommandLineTools/SDKs/
          fi

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Get date of latest commit'
        id: date
        run: echo "date=$(git log -n 1 --date=short --format=format:%cd | sed 's/\(....\)-\(..\)-\(..\).*/\1\2\3/')" >> $GITHUB_OUTPUT

        # Since Homebrew doesn't provide binaries for old versions, we have to compile our own:
      - name: 'Download SDL2 sources'
        run: |
          curl https://www.libsdl.org/release/SDL2-$SDL_VERSION.tar.gz | tar xvf -

      - name: 'Build SDL2'
        run: |
          cd SDL2-$SDL_VERSION
          ./configure CC="sh ../scripts/build-uni.sh"
          make
          make install
          rm -rf arm64 x64
          cd ..
      
      - name: 'Download libflac and libogg sources'
        run: |
          curl https://ftp.osuosl.org/pub/xiph/releases/flac/flac-$FLAC_VERSION.tar.xz | tar -xvf -
          curl https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-$LIBOGG_VERSION.tar.gz | tar -xvf -

      - name: 'Build libflac'
        run: |
          cd libogg-$LIBOGG_VERSION
          mkdir build
          cd build
          ../configure CC="sh $PWD/../../scripts/build-uni.sh" LDFLAGS="-L/usr/local/lib"
          make
          make install
          cd ../../flac-$FLAC_VERSION
          mkdir build
          cd build
          ../configure CC="sh $PWD/../../scripts/build-uni.sh" LDFLAGS="-L/usr/local/lib"
          make
          make install
          cd ../..

      - name: 'Build package'
        run: |
          autoreconf -i
          mkdir -p build
          cd build
          ../configure --with-flac
          make CFLAGS="-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.9.sdk -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers"
          mkdir -p ../buildarm
          cd ../buildarm
          ../configure --with-flac
          make LDFLAGS="-arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk" CFLAGS="-arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers" OBJCFLAGS="-arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers"
          cd ..
          lipo -create -o schismtracker buildarm/schismtracker build/schismtracker
          strip -S schismtracker
          cd sys/macosx/Schism_Tracker.app/Contents/
          sed -i .bak "s;<string>CFBundle.*Version.*</string>;<string>$(date +%Y%m%d)</string>;" Info.plist
          rm Info.plist.bak
          mkdir MacOS
          cp ../../../../schismtracker MacOS
          cp /usr/local/lib/libSDL2-2.0.0.dylib Resources
          cp /usr/local/lib/libFLAC.12.dylib Resources
          cp /usr/local/lib/libogg.0.dylib Resources
          strip -S Resources/libSDL2-2.0.0.dylib
          strip -S Resources/libFLAC.12.dylib
          strip -S Resources/libogg.0.dylib
          install_name_tool -change /usr/local/lib/libogg.0.dylib @loader_path/../Resources/libogg.0.dylib Resources/libFLAC.12.dylib
          cd MacOS
          install_name_tool -change /usr/local/lib/libSDL2-2.0.0.dylib @executable_path/../Resources/libSDL2-2.0.0.dylib schismtracker
          install_name_tool -change /usr/local/lib/libFLAC.12.dylib @executable_path/../Resources/libFLAC.12.dylib schismtracker
          install_name_tool -change /usr/local/lib/libogg.0.dylib @executable_path/../Resources/libogg.0.dylib schismtracker
          cd ../../../../..
          cp -r sys/macosx/Schism_Tracker.app Schism\ Tracker.app
          cp docs/configuration.md .
          wget https://raw.githubusercontent.com/xiph/flac/master/COPYING.Xiph
          zip -r schismtracker.zip configuration.md COPYING COPYING.Xiph README.md Schism\ Tracker.app

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: schismtracker-${{ steps.date.outputs.date }}-macos
          path: schismtracker.zip
