name: OS X (PowerPC)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  osxppc:
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.5
      SDL_VERSION: 2.0.3
      FLAC_VERSION: 1.4.3
      LIBOGG_VERSION: 1.3.5

    steps:
      - name: 'Install wget'
        run: |
          brew install automake zip wget

      - name: 'Grab needed binaries'
        run: |
          # todo: find a more permanent place to store these
          wget -O schism-macppc-bins.zip "https://www.dropbox.com/scl/fi/trq99fq51p13nh8tajpwa/schism-macppc-bins.zip?rlkey=xemvhpmm1ci0dnseawmanr749&st=g4qteuny&dl=1"
          unzip schism-macppc-bins.zip -d "schism-macppc-bins"

      - name: 'Install binaries to prefix'
        run: |
          mkdir "$HOME/ppc"
          cd schism-macppc-bins
          tar -xvf "Xcode3as.tar.gz" -C "$HOME/ppc"
          tar -xvf "Xcode3gcc42.tar.gz" -C "$HOME/ppc"
          tar -xvf "Xcode3ld.tar.gz" -C "$HOME/ppc"
          tar -xvf "Xcode105SDK.tar.gz" -C "$HOME/ppc"
          tar -xvf "OSX108INT.tar.gz" -C "$HOME/ppc"
          mkdir "/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec/as/ppc"
          cp "$HOME/ppc/usr/libexec/gcc/darwin/ppc/as" "/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec/as/ppc/as"
          cd ..

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Get date of latest commit'
        id: date
        run: echo "date=$(git log -n 1 --date=short --format=format:%cd | sed 's/\(....\)-\(..\)-\(..\).*/\1\2\3/')" >> $GITHUB_OUTPUT

      - name: 'Download SDL2 sources'
        run: |
          curl https://www.libsdl.org/release/SDL2-$SDL_VERSION.tar.gz | tar xvf -

      - name: 'Patch SDL2'
        run: |
          wget -O SDL2-2.0.3_OSX_105.patch "https://gist.github.com/miniupnp/a8f474c504eaa3ad9135/raw/7481973a1cd11b98ec01806e3729c9b96b5310a4/SDL2-2.0.3_OSX_105.patch"
          patch -p0 < SDL2-2.0.3_OSX_105.patch

      - name: 'Build SDL2'
        run: |
          export PATH="$HOME/ppc/usr/bin:$PATH"
          cd SDL2-2.0.3
          mkdir build
          cd build
          ../configure CC=powerpc-apple-darwin10-gcc-4.2.1 CPP=powerpc-apple-darwin10-cpp-4.2.1 OBJC=powerpc-apple-darwin10-gcc-4.2.1 CXX=powerpc-apple-darwin10-g++-4.2.1 CFLAGS="" CPPFLAGS="-isysroot $HOME/ppc/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5" LDFLAGS="-F$HOME/ppc/SDKs/MacOSX10.5.sdk/System/Library/Frameworks -L/usr/lib -L/usr/lib/system -Wl,-syslibroot,$HOME/ppc/SDKs/MacOSX10.5.sdk" --host=powerpc-apple-darwin10 --prefix="$HOME/ppcprefix" --disable-rpath --disable-alsa-shared --disable-pulseaudio-shared --disable-x11-shared --disable-esd --disable-video-wayland --disable-alsa --disable-dbus --disable-nas --disable-pulseaudio --disable-video-x11 --disable-haptic --disable-rpath
          make
          make install
          cd ../..

      - name: 'Download libflac and libogg sources'
        run: |
          curl https://ftp.osuosl.org/pub/xiph/releases/flac/flac-$FLAC_VERSION.tar.xz | tar -xvf -
          curl https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-$LIBOGG_VERSION.tar.gz | tar -xvf -

      - name: 'Build libflac'
        run: |
          export PATH="$HOME/ppc/usr/bin:$PATH"
          cd libogg-$LIBOGG_VERSION
          mkdir build
          cd build
          ../configure CC=powerpc-apple-darwin10-gcc-4.2.1 CPP=powerpc-apple-darwin10-cpp-4.2.1 OBJC=powerpc-apple-darwin10-gcc-4.2.1 CXX=powerpc-apple-darwin10-g++-4.2.1 CFLAGS="" CPPFLAGS="-isysroot $HOME/ppc/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5" LDFLAGS="-F$HOME/ppc/SDKs/MacOSX10.5.sdk/System/Library/Frameworks -Wl,-syslibroot,$HOME/ppc/SDKs/MacOSX10.5.sdk" --host=powerpc-apple-darwin10 --prefix="$HOME/ppcprefix"
          make
          make install
          cd ../../flac-$FLAC_VERSION
          mkdir build
          cd build
          ../configure CC=powerpc-apple-darwin10-gcc-4.2.1 CPP=powerpc-apple-darwin10-cpp-4.2.1 OBJC=powerpc-apple-darwin10-gcc-4.2.1 CXX=powerpc-apple-darwin10-g++-4.2.1 CFLAGS="" CPPFLAGS="-isysroot $HOME/ppc/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5" LDFLAGS="-F$HOME/ppc/SDKs/MacOSX10.5.sdk/System/Library/Frameworks -Wl,-syslibroot,$HOME/ppc/SDKs/MacOSX10.5.sdk" --host=powerpc-apple-darwin10 --prefix="$HOME/ppcprefix"
          make
          make install
          cd ../..

      - name: 'Build Schism'
        run: |
          export PATH="$HOME/ppc/usr/bin:$PATH"
          export PKG_CONFIG_PATH="$HOME/ppcprefix/libs/pkgconfig"
          autoreconf -I"$HOME/ppcprefix/share/aclocal" -i
          mkdir build
          cd build
          ../configure CC=powerpc-apple-darwin10-gcc-4.2.1 CPP=powerpc-apple-darwin10-cpp-4.2.1 OBJC=powerpc-apple-darwin10-gcc-4.2.1 CXX=powerpc-apple-darwin10-g++-4.2.1 CFLAGS="" CPPFLAGS="-isysroot $HOME/ppc/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5" LDFLAGS="-F$HOME/ppc/SDKs/MacOSX10.5.sdk/System/Library/Frameworks -L$HOME/ppcprefix/lib -Wl,-syslibroot,$HOME/ppc/SDKs/MacOSX10.5.sdk" --host=powerpc-apple-darwin10 --prefix="$HOME/ppcprefix" --with-sdl-prefix="$HOME/ppcprefix"
          make
          cd ..
          cd sys/macosx/Schism_Tracker.app/Contents/
          sed -i .bak "s;<string>CFBundle.*Version.*</string>;<string>$(date +%Y%m%d)</string>;" Info.plist
          rm Info.plist.bak
          mkdir MacOS
          cp ../../../../build/schismtracker MacOS
          cp $HOME/ppcprefix/lib/libSDL2-2.0.0.dylib Resources
          cp $HOME/ppcprefix/lib/libFLAC.12.dylib Resources
          cp $HOME/ppcprefix/lib/libogg.0.dylib Resources
          # no strip needed here, we explicitly disable `-g` because it breaks builds somehow
          $HOME/ppc/usr/bin/install_name_tool -change $HOME/ppcprefix/lib/libogg.0.dylib @loader_path/../Resources/libogg.0.dylib Resources/libFLAC.12.dylib
          cd MacOS
          $HOME/ppc/usr/bin/install_name_tool -change $HOME/ppcprefix/lib/libSDL2-2.0.0.dylib @executable_path/../Resources/libSDL2-2.0.0.dylib schismtracker
          $HOME/ppc/usr/bin/install_name_tool -change $HOME/ppcprefix/lib/libFLAC.12.dylib @executable_path/../Resources/libFLAC.12.dylib schismtracker
          $HOME/ppc/usr/bin/install_name_tool -change $HOME/ppcprefix/lib/libogg.0.dylib @executable_path/../Resources/libogg.0.dylib schismtracker
          cd ../../../../..
          cp -r sys/macosx/Schism_Tracker.app Schism\ Tracker.app
          cp docs/configuration.md .
          wget https://raw.githubusercontent.com/xiph/flac/master/COPYING.Xiph
          zip -r schismtracker.zip configuration.md COPYING COPYING.Xiph README.md Schism\ Tracker.app

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: schismtracker-${{ steps.date.outputs.date }}-macppc
          path: schismtracker.zip
